INSERT INTO CATEGORY (id, category_name, created_at, updated_at)
SELECT 1, '인증게시판', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE id = 1);

INSERT INTO CATEGORY (id, category_name, created_at, updated_at)
SELECT 2, '정보공유게시판', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE id = 2);

INSERT INTO CATEGORY (id, category_name, created_at, updated_at)
SELECT 3, '자유게시판', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE id = 3);
